/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_interface = 2,
  anon_sym_node = 3,
  anon_sym_implements = 4,
  anon_sym_COMMA = 5,
  anon_sym_edge = 6,
  anon_sym_COLON = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  sym_nullable_marker = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_enum = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_AT = 17,
  anon_sym_EQ = 18,
  anon_sym_DOT_DOT = 19,
  sym_enum_value = 20,
  sym_string = 21,
  sym_float = 22,
  sym_integer = 23,
  anon_sym_true = 24,
  anon_sym_false = 25,
  sym_type_identifier = 26,
  sym_comment = 27,
  sym_block_comment = 28,
  sym_source_file = 29,
  sym__declaration = 30,
  sym_interface_declaration = 31,
  sym_node_declaration = 32,
  sym_implements_clause = 33,
  sym_edge_declaration = 34,
  sym_declaration_body = 35,
  sym_property = 36,
  sym_type = 37,
  sym__core_type = 38,
  sym_list_type = 39,
  sym_enum_type = 40,
  sym_named_type = 41,
  sym_annotation = 42,
  sym_annotation_arguments = 43,
  sym__annotation_argument = 44,
  sym_kwarg = 45,
  sym_range = 46,
  sym__literal = 47,
  sym__number = 48,
  sym_boolean = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_node_declaration_repeat1 = 51,
  aux_sym_implements_clause_repeat1 = 52,
  aux_sym_declaration_body_repeat1 = 53,
  aux_sym_enum_type_repeat1 = 54,
  aux_sym_annotation_arguments_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_interface] = "interface",
  [anon_sym_node] = "node",
  [anon_sym_implements] = "implements",
  [anon_sym_COMMA] = ",",
  [anon_sym_edge] = "edge",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_nullable_marker] = "nullable_marker",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_enum] = "enum",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT_DOT] = "..",
  [sym_enum_value] = "enum_value",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_type_identifier] = "type_identifier",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_interface_declaration] = "interface_declaration",
  [sym_node_declaration] = "node_declaration",
  [sym_implements_clause] = "implements_clause",
  [sym_edge_declaration] = "edge_declaration",
  [sym_declaration_body] = "declaration_body",
  [sym_property] = "property",
  [sym_type] = "type",
  [sym__core_type] = "_core_type",
  [sym_list_type] = "list_type",
  [sym_enum_type] = "enum_type",
  [sym_named_type] = "named_type",
  [sym_annotation] = "annotation",
  [sym_annotation_arguments] = "annotation_arguments",
  [sym__annotation_argument] = "_annotation_argument",
  [sym_kwarg] = "kwarg",
  [sym_range] = "range",
  [sym__literal] = "_literal",
  [sym__number] = "_number",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_node_declaration_repeat1] = "node_declaration_repeat1",
  [aux_sym_implements_clause_repeat1] = "implements_clause_repeat1",
  [aux_sym_declaration_body_repeat1] = "declaration_body_repeat1",
  [aux_sym_enum_type_repeat1] = "enum_type_repeat1",
  [aux_sym_annotation_arguments_repeat1] = "annotation_arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_interface] = anon_sym_interface,
  [anon_sym_node] = anon_sym_node,
  [anon_sym_implements] = anon_sym_implements,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_edge] = anon_sym_edge,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_nullable_marker] = sym_nullable_marker,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_enum_value] = sym_enum_value,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_type_identifier] = sym_type_identifier,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_interface_declaration] = sym_interface_declaration,
  [sym_node_declaration] = sym_node_declaration,
  [sym_implements_clause] = sym_implements_clause,
  [sym_edge_declaration] = sym_edge_declaration,
  [sym_declaration_body] = sym_declaration_body,
  [sym_property] = sym_property,
  [sym_type] = sym_type,
  [sym__core_type] = sym__core_type,
  [sym_list_type] = sym_list_type,
  [sym_enum_type] = sym_enum_type,
  [sym_named_type] = sym_named_type,
  [sym_annotation] = sym_annotation,
  [sym_annotation_arguments] = sym_annotation_arguments,
  [sym__annotation_argument] = sym__annotation_argument,
  [sym_kwarg] = sym_kwarg,
  [sym_range] = sym_range,
  [sym__literal] = sym__literal,
  [sym__number] = sym__number,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_node_declaration_repeat1] = aux_sym_node_declaration_repeat1,
  [aux_sym_implements_clause_repeat1] = aux_sym_implements_clause_repeat1,
  [aux_sym_declaration_body_repeat1] = aux_sym_declaration_body_repeat1,
  [aux_sym_enum_type_repeat1] = aux_sym_enum_type_repeat1,
  [aux_sym_annotation_arguments_repeat1] = aux_sym_annotation_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_interface] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_node] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_implements] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_edge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_nullable_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_interface_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_node_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_implements_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_body] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__core_type] = {
    .visible = false,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_type] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__annotation_argument] = {
    .visible = false,
    .named = true,
  },
  [sym_kwarg] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_implements_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotation_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_from = 1,
  field_name = 2,
  field_to = 3,
  field_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_name] = "name",
  [field_to] = "to",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_from, 3},
    {field_name, 1},
    {field_to, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 10,
  [14] = 11,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 21,
  [28] = 28,
  [29] = 29,
  [30] = 23,
  [31] = 31,
  [32] = 24,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 48,
  [60] = 51,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 78,
  [88] = 88,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 1,
        '(', 21,
        ')', 22,
        ',', 13,
        '-', 8,
        '.', 6,
        '/', 2,
        ':', 14,
        '=', 24,
        '?', 18,
        '@', 23,
        '[', 19,
        ']', 20,
        '{', 16,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(31);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_nullable_marker);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_enum_value);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(6);
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'm') ADVANCE(9);
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_edge);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_node);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(31);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_interface);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_implements);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_interface] = ACTIONS(1),
    [anon_sym_node] = ACTIONS(1),
    [anon_sym_implements] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_edge] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_nullable_marker] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(79),
    [sym__declaration] = STATE(5),
    [sym_interface_declaration] = STATE(5),
    [sym_node_declaration] = STATE(5),
    [sym_edge_declaration] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_interface] = ACTIONS(7),
    [anon_sym_node] = ACTIONS(9),
    [anon_sym_edge] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT_DOT,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_float,
    ACTIONS(23), 1,
      sym_integer,
    STATE(89), 1,
      sym__number,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 5,
      sym__annotation_argument,
      sym_kwarg,
      sym_range,
      sym__literal,
      sym_boolean,
  [37] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_DOT_DOT,
    ACTIONS(21), 1,
      sym_float,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(29), 1,
      sym_string,
    STATE(89), 1,
      sym__number,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 5,
      sym__annotation_argument,
      sym_kwarg,
      sym_range,
      sym__literal,
      sym_boolean,
  [74] = 9,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_DOT_DOT,
    ACTIONS(21), 1,
      sym_float,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(31), 1,
      sym_string,
    STATE(89), 1,
      sym__number,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 5,
      sym__annotation_argument,
      sym_kwarg,
      sym_range,
      sym__literal,
      sym_boolean,
  [108] = 6,
    ACTIONS(7), 1,
      anon_sym_interface,
    ACTIONS(9), 1,
      anon_sym_node,
    ACTIONS(11), 1,
      anon_sym_edge,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(6), 5,
      sym__declaration,
      sym_interface_declaration,
      sym_node_declaration,
      sym_edge_declaration,
      aux_sym_source_file_repeat1,
  [132] = 6,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_interface,
    ACTIONS(40), 1,
      anon_sym_node,
    ACTIONS(43), 1,
      anon_sym_edge,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(6), 5,
      sym__declaration,
      sym_interface_declaration,
      sym_node_declaration,
      sym_edge_declaration,
      aux_sym_source_file_repeat1,
  [156] = 6,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_AT,
    STATE(44), 1,
      sym_declaration_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(8), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [180] = 6,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_declaration_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(10), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
    ACTIONS(52), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [204] = 6,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_enum,
    ACTIONS(58), 1,
      sym_type_identifier,
    STATE(29), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(40), 4,
      sym__core_type,
      sym_list_type,
      sym_enum_type,
      sym_named_type,
  [227] = 4,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(10), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
  [246] = 4,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_annotation_arguments,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
      anon_sym_AT,
  [265] = 7,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_implements,
    ACTIONS(71), 1,
      anon_sym_AT,
    STATE(37), 1,
      sym_declaration_body,
    STATE(70), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(13), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
  [289] = 5,
    ACTIONS(75), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(60), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(73), 2,
      anon_sym_implements,
      sym_identifier,
    STATE(13), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
  [309] = 5,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_annotation_arguments,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(78), 2,
      anon_sym_implements,
      sym_identifier,
    ACTIONS(65), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
  [329] = 5,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_enum,
    ACTIONS(58), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(90), 4,
      sym__core_type,
      sym_list_type,
      sym_enum_type,
      sym_named_type,
  [349] = 7,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_implements,
    ACTIONS(71), 1,
      anon_sym_AT,
    STATE(41), 1,
      sym_declaration_body,
    STATE(68), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(12), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
  [373] = 5,
    ACTIONS(84), 1,
      sym_integer,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(82), 2,
      sym_string,
      sym_float,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 2,
      sym__literal,
      sym_boolean,
  [393] = 5,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_property,
      sym_annotation,
      aux_sym_declaration_body_repeat1,
  [412] = 5,
    ACTIONS(71), 1,
      anon_sym_AT,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_property,
      sym_annotation,
      aux_sym_declaration_body_repeat1,
  [431] = 5,
    ACTIONS(71), 1,
      anon_sym_AT,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    STATE(19), 3,
      sym_property,
      sym_annotation,
      aux_sym_declaration_body_repeat1,
  [450] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
      anon_sym_AT,
  [463] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
      anon_sym_AT,
  [476] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
      anon_sym_AT,
  [489] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
      anon_sym_LBRACE,
      anon_sym_AT,
  [502] = 3,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(110), 5,
      anon_sym_RBRACE,
      sym_nullable_marker,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [517] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(114), 2,
      anon_sym_implements,
      sym_identifier,
    ACTIONS(104), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
  [531] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(116), 2,
      anon_sym_implements,
      sym_identifier,
    ACTIONS(102), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
  [545] = 4,
    ACTIONS(71), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(13), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
  [561] = 4,
    ACTIONS(71), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(28), 2,
      sym_annotation,
      aux_sym_node_declaration_repeat1,
  [577] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(122), 2,
      anon_sym_implements,
      sym_identifier,
    ACTIONS(106), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
  [591] = 5,
    ACTIONS(126), 1,
      sym_float,
    ACTIONS(128), 1,
      sym_integer,
    STATE(65), 1,
      sym__number,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(124), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [609] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(130), 2,
      anon_sym_implements,
      sym_identifier,
    ACTIONS(108), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
  [623] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(132), 5,
      anon_sym_RBRACE,
      sym_nullable_marker,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [635] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(134), 5,
      anon_sym_RBRACE,
      sym_nullable_marker,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [647] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(136), 5,
      anon_sym_RBRACE,
      sym_nullable_marker,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [659] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(138), 5,
      anon_sym_RBRACE,
      sym_nullable_marker,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [671] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [682] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [693] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [704] = 3,
    ACTIONS(148), 1,
      sym_nullable_marker,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(146), 3,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [717] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [728] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [739] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [750] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(52), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [761] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      anon_sym_interface,
      anon_sym_node,
      anon_sym_edge,
  [772] = 4,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [786] = 3,
    ACTIONS(164), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [798] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_annotation_arguments_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [812] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [826] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(174), 3,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [836] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_annotation_arguments_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [850] = 4,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_annotation_arguments_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [864] = 4,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [878] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [892] = 4,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [906] = 4,
    ACTIONS(192), 1,
      sym_float,
    ACTIONS(194), 1,
      sym_integer,
    STATE(61), 1,
      sym__number,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [920] = 4,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [934] = 3,
    ACTIONS(203), 1,
      anon_sym_DOT_DOT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [946] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_annotation_arguments_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [960] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_annotation_arguments_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [974] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(124), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [983] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [992] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1001] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1010] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1019] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1028] = 3,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_declaration_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1039] = 3,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_declaration_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1050] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1059] = 3,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_declaration_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1070] = 2,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1078] = 2,
    ACTIONS(217), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1086] = 2,
    ACTIONS(219), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1094] = 2,
    ACTIONS(221), 1,
      sym_enum_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1102] = 2,
    ACTIONS(223), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1110] = 2,
    ACTIONS(225), 1,
      sym_enum_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1118] = 2,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1126] = 2,
    ACTIONS(229), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1134] = 2,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1142] = 2,
    ACTIONS(233), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1150] = 2,
    ACTIONS(235), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1158] = 2,
    ACTIONS(237), 1,
      anon_sym_DASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1166] = 2,
    ACTIONS(239), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1174] = 2,
    ACTIONS(241), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1182] = 2,
    ACTIONS(243), 1,
      sym_integer,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1190] = 2,
    ACTIONS(245), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1198] = 2,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1206] = 2,
    ACTIONS(249), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1214] = 2,
    ACTIONS(251), 1,
      anon_sym_DOT_DOT,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [1222] = 2,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 156,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 204,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 246,
  [SMALL_STATE(12)] = 265,
  [SMALL_STATE(13)] = 289,
  [SMALL_STATE(14)] = 309,
  [SMALL_STATE(15)] = 329,
  [SMALL_STATE(16)] = 349,
  [SMALL_STATE(17)] = 373,
  [SMALL_STATE(18)] = 393,
  [SMALL_STATE(19)] = 412,
  [SMALL_STATE(20)] = 431,
  [SMALL_STATE(21)] = 450,
  [SMALL_STATE(22)] = 463,
  [SMALL_STATE(23)] = 476,
  [SMALL_STATE(24)] = 489,
  [SMALL_STATE(25)] = 502,
  [SMALL_STATE(26)] = 517,
  [SMALL_STATE(27)] = 531,
  [SMALL_STATE(28)] = 545,
  [SMALL_STATE(29)] = 561,
  [SMALL_STATE(30)] = 577,
  [SMALL_STATE(31)] = 591,
  [SMALL_STATE(32)] = 609,
  [SMALL_STATE(33)] = 623,
  [SMALL_STATE(34)] = 635,
  [SMALL_STATE(35)] = 647,
  [SMALL_STATE(36)] = 659,
  [SMALL_STATE(37)] = 671,
  [SMALL_STATE(38)] = 682,
  [SMALL_STATE(39)] = 693,
  [SMALL_STATE(40)] = 704,
  [SMALL_STATE(41)] = 717,
  [SMALL_STATE(42)] = 728,
  [SMALL_STATE(43)] = 739,
  [SMALL_STATE(44)] = 750,
  [SMALL_STATE(45)] = 761,
  [SMALL_STATE(46)] = 772,
  [SMALL_STATE(47)] = 786,
  [SMALL_STATE(48)] = 798,
  [SMALL_STATE(49)] = 812,
  [SMALL_STATE(50)] = 826,
  [SMALL_STATE(51)] = 836,
  [SMALL_STATE(52)] = 850,
  [SMALL_STATE(53)] = 864,
  [SMALL_STATE(54)] = 878,
  [SMALL_STATE(55)] = 892,
  [SMALL_STATE(56)] = 906,
  [SMALL_STATE(57)] = 920,
  [SMALL_STATE(58)] = 934,
  [SMALL_STATE(59)] = 946,
  [SMALL_STATE(60)] = 960,
  [SMALL_STATE(61)] = 974,
  [SMALL_STATE(62)] = 983,
  [SMALL_STATE(63)] = 992,
  [SMALL_STATE(64)] = 1001,
  [SMALL_STATE(65)] = 1010,
  [SMALL_STATE(66)] = 1019,
  [SMALL_STATE(67)] = 1028,
  [SMALL_STATE(68)] = 1039,
  [SMALL_STATE(69)] = 1050,
  [SMALL_STATE(70)] = 1059,
  [SMALL_STATE(71)] = 1070,
  [SMALL_STATE(72)] = 1078,
  [SMALL_STATE(73)] = 1086,
  [SMALL_STATE(74)] = 1094,
  [SMALL_STATE(75)] = 1102,
  [SMALL_STATE(76)] = 1110,
  [SMALL_STATE(77)] = 1118,
  [SMALL_STATE(78)] = 1126,
  [SMALL_STATE(79)] = 1134,
  [SMALL_STATE(80)] = 1142,
  [SMALL_STATE(81)] = 1150,
  [SMALL_STATE(82)] = 1158,
  [SMALL_STATE(83)] = 1166,
  [SMALL_STATE(84)] = 1174,
  [SMALL_STATE(85)] = 1182,
  [SMALL_STATE(86)] = 1190,
  [SMALL_STATE(87)] = 1198,
  [SMALL_STATE(88)] = 1206,
  [SMALL_STATE(89)] = 1214,
  [SMALL_STATE(90)] = 1222,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_declaration, 6, 0, 4),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_declaration, 7, 0, 4),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_declaration_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_node_declaration_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 2, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 3, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_arguments, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_arguments, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_arguments, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation_arguments, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 3, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 3),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation_arguments, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation_arguments, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 4, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 5, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_declaration, 4, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_body, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_declaration, 3, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_declaration, 3, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_declaration, 5, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_declaration, 8, 0, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_body, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__annotation_argument, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implements_clause, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotation_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_annotation_arguments_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_implements_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_implements_clause_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implements_clause, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwarg, 3, 0, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
