id = "omnigraph"
name = "OmniGraph"
version = "0.1.0"
schema_version = 1
authors = ["Andrew Jones <andrew@iceberglab.xyz>"]
description = "Syntax highlighting for the OmniGraph schema (.pg) and query (.gq) languages"
repository = "https://github.com/ModernRelay/omnigraph"

[grammars.pg]
repository = "file:///Users/andjones/Documents/repos/omnigraph"
rev = "239884ffa5636fb9842c3b2dc35e9bceaca34077"
path = "editors/tree-sitter-pg"

[grammars.gq]
repository = "file:///Users/andjones/Documents/repos/omnigraph"
rev = "9911fbfae0131c336c47372ae7dc32187137478a"
path = "editors/tree-sitter-gq"
